(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.ustanovka = function() {
	this.initialize(img.ustanovka);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2603,2220);


(lib.Шарики = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("BanochkUS");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("AIkqWQCGCQgGALQgDAFAaAgQAaAzgDBgQgDBhAGBxQACA2ACASQgCgPgSBkQgFAdADAfQABAPgQAeQgZAxg5BMQgEAFgQAOQgKAIABAMQAAAEASCHQARB+gCAPQgCAPgKAXQgEALgEAKQABADgoAwQgvA6gxAtQhiA2hkAqQiWA+hSAAQiIABifg9QjShShFiTQgoiLADhZQANhXABg4QgOgwgxgyQgwgxgFgVQgIghgBgRQAAgZAAgbQgBgfgLg4QgOhCgBgKQgFgygCg1QgChSAJgtQAPhGAOgrQAWhBAfgrQAQgUAHgEQABAAAKABQAOAAAwhFQA+hcARgXQAWgbAygtQAxgsBsgZQA+gOB7gPQBYgLBtAHQB0AHAsAXQAxAZASAOQAYASAyA3QArAuAcA3QAbA4ABAAg");
	this.shape.setTransform(372.8,796.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.008)").s().p("AkKOIQjShShFiTQgoiLADhZQANhXABg4QgOgwgxgyQgwgxgFgVQgIghgBgRIAAg0QgBgfgLg4QgOhCgBgKQgFgygCg1QgChSAJgtQAPhGAOgrQAWhBAfgrQAQgUAHgEIALABQAOAAAwhFQA+hcARgXQAWgbAygtQAxgsBsgZQA+gOB7gPQBYgLBtAHQB0AHAsAXQAxAZASAOQAYASAyA3QArAuAcA3IAcA4QCGCQgGALQgDAFAaAgQAaAzgDBgQgDBhAGBxIAEBIQgCgPgSBkQgFAdADAfQABAPgQAeQgZAxg5BMQgEAFgQAOQgKAIABAMIASCLQARB+gCAPQgCAPgKAXIgIAVQABADgoAwQgvA6gxAtQhiA2hkAqQiWA+hSAAIgDAAQiHAAidg8g");
	this.shape_1.setTransform(372.8,796.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("AIkqWQCGCQgGALQgDAFAaAgQAaAzgDBgQgDBhAGBxQACA2ACASQgCgPgSBkQgFAdADAfQABAPgQAeQgZAxg5BMQgEAFgQAOQgKAIABAMQAAAEASCHQARB+gCAPQgCAPgKAXQgEALgEAKQABADgoAwQgvA6gxAtQhiA2hkAqQiWA+hSAAQiIABifg9QjShShFiTQgoiLADhZQANhXABg4QgOgwgxgyQgwgxgFgVQgIghgBgRQAAgZAAgbQgBgfgLg4QgOhCgBgKQgFgygCg1QgChSAJgtQAPhGAOgrQAWhBAfgrQAQgUAHgEQABAAAKABQAOAAAwhFQA+hcARgXQAWgbAygtQAxgsBsgZQA+gOB7gPQBYgLBtAHQB0AHAsAXQAxAZASAOQAYASAyA3QArAuAcA3QAbA4ABAAg");
	this.shape_2.setTransform(372.8,796.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("AkKOIQjShShFiTQgoiLADhZQANhXABg4QgOgwgxgyQgwgxgFgVQgIghgBgRIAAg0QgBgfgLg4QgOhCgBgKQgFgygCg1QgChSAJgtQAPhGAOgrQAWhBAfgrQAQgUAHgEIALABQAOAAAwhFQA+hcARgXQAWgbAygtQAxgsBsgZQA+gOB7gPQBYgLBtAHQB0AHAsAXQAxAZASAOQAYASAyA3QArAuAcA3IAcA4QCGCQgGALQgDAFAaAgQAaAzgDBgQgDBhAGBxIAEBIQgCgPgSBkQgFAdADAfQABAPgQAeQgZAxg5BMQgEAFgQAOQgKAIABAMIASCLQARB+gCAPQgCAPgKAXIgIAVQABADgoAwQgvA6gxAtQhiA2hkAqQiWA+hSAAIgDAAQiHAAidg8g");
	this.shape_3.setTransform(372.8,796.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("AkKOIQjShShFiTQgoiLADhZQANhXABg4QgOgwgxgyQgwgxgFgVQgIghgBgRIAAg0QgBgfgLg4QgOhCgBgKQgFgygCg1QgChSAJgtQAPhGAOgrQAWhBAfgrQAQgUAHgEIALABQAOAAAwhFQA+hcARgXQAWgbAygtQAxgsBsgZQA+gOB7gPQBYgLBtAHQB0AHAsAXQAxAZASAOQAYASAyA3QArAuAcA3IAcA4QCGCQgGALQgDAFAaAgQAaAzgDBgQgDBhAGBxIAEBIQgCgPgSBkQgFAdADAfQABAPgQAeQgZAxg5BMQgEAFgQAOQgKAIABAMIASCLQARB+gCAPQgCAPgKAXIgIAVQABADgoAwQgvA6gxAtQhiA2hkAqQiWA+hSAAIgDAAQiHAAidg8g");
	this.shape_4.setTransform(372.8,796.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(299,699,147.7,194.9);


(lib.Таймер = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("Sekundomer");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("EAfWgh/QACgCCMCDQCNCDgCAAQgBAAAvBLQAvBLgDAAQgEAAA+BgQA+BhAAgDQCHEMgFACQgEACApCuQAoCsADADQACACALCQQAKCQgDAAQgEAABCBgQBCBgACgCQACgCAkBuQAjBugDACQgDABA1DxQA1DugDgBQgCgBgXF9QgXF9gCAAQgDAAgnBkQgTAygTAyIsCOsQsNH3AAgCQAAgBqSCwQqUCwgDgBQgFgDnuANQgCAAm0hgQmyhgACACQABABk6hpQk7hqgDAAQgFAAnbmRQgyg6gyg7Qhkh0AAADQAAAChsjWQhujZgCgBQgDgBhIj1QhJj0gCAAQgFAAAZpZQAihVAhhWQBCiqgDABQgDACgWhpQgXhqgCAAQgFAAgZl8QAAAFAyjrQAAgDAyjFQAuhlAuhjQBbjHgDgCQgDgBCEi/QCFi9gCABQAnglAogmQBRhMAAABQAJiVAIiXQAQkugDACQgCABA0hMQA1hMgDABQgFACBzhmQgCACBJgfQBJgfgEAAQgBAAA3ghQA6gigCgDQgBgDZChIQZBhJgBgCQgBgDBtAHQBvAHABgBQACgCBeA0QBeAzAAgBQBsCvACAFQACADAYEDQAMCBAMCBg");
	this.shape.setTransform(1473.7,301.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("EgOQAtLQmyhgACACQABABk6hpQk7hqgDAAQgFAAnbmRIhkh1Qhkh0AAADQAAAChsjWQhujZgCgBQgDgBhIj1QhJj0gCAAQgFAAAZpZIBDirQBCiqgDABQgDACgWhpQgXhqgCAAQgFAAgZl8QAAADAyjpIAyjIIBcjIQBbjHgDgCQgDgBCEi/ICDi8IBPhLQBRhMAAABIARksQAQkugDACQgCABA0hMQA1hMgDABQgFACBzhmQgCACBJgfQBJgfgEAAQgBAAA3ghQA6gigCgDQgBgDZChIQZBhJgBgCQgBgDBtAHQBvAHABgBQACgCBeA0QBeAzAAgBIBuC0QACADAYEDIAYECQACgCCMCDQCNCDgCAAQgBAAAvBLQAvBLgDAAQgEAAA+BgQA+BhAAgDQCHEMgFACQgEACApCuQAoCsADADQACACALCQQAKCQgDAAQgEAABCBgQBCBgACgCQACgCAkBuQAjBugDACQgDABA1DxQA1DugDgBQgCgBgXF9QgXF9gCAAQgDAAgnBkIgmBkIsCOsQsNH3AAgCQAAgBqSCwQqUCwgDgBQgFgDnuANIm2hggEguLgHuIAAAAIAAAAg");
	this.shape_1.setTransform(1473.7,301.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("EAfWgh/QACgCCMCDQCNCDgCAAQgBAAAvBLQAvBLgDAAQgEAAA+BgQA+BhAAgDQCHEMgFACQgEACApCuQAoCsADADQACACALCQQAKCQgDAAQgEAABCBgQBCBgACgCQACgCAkBuQAjBugDACQgDABA1DxQA1DugDgBQgCgBgXF9QgXF9gCAAQgDAAgnBkQgTAygTAyIsCOsQsNH3AAgCQAAgBqSCwQqUCwgDgBQgFgDnuANQgCAAm0hgQmyhgACACQABABk6hpQk7hqgDAAQgFAAnbmRQgyg6gyg7Qhkh0AAADQAAAChsjWQhujZgCgBQgDgBhIj1QhJj0gCAAQgFAAAZpZQAihVAhhWQBCiqgDABQgDACgWhpQgXhqgCAAQgFAAgZl8QAAAFAyjrQAAgDAyjFQAuhlAuhjQBbjHgDgCQgDgBCEi/QCFi9gCABQAnglAogmQBRhMAAABQAJiVAIiXQAQkugDACQgCABA0hMQA1hMgDABQgFACBzhmQgCACBJgfQBJgfgEAAQgBAAA3ghQA6gigCgDQgBgDZChIQZBhJgBgCQgBgDBtAHQBvAHABgBQACgCBeA0QBeAzAAgBQBsCvACAFQACADAYEDQAMCBAMCBg");
	this.shape_2.setTransform(1473.7,301.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("EgOQAtLQmyhgACACQABABk6hpQk7hqgDAAQgFAAnbmRIhkh1Qhkh0AAADQAAAChsjWQhujZgCgBQgDgBhIj1QhJj0gCAAQgFAAAZpZIBDirQBCiqgDABQgDACgWhpQgXhqgCAAQgFAAgZl8QAAADAyjpIAyjIIBcjIQBbjHgDgCQgDgBCEi/ICDi8IBPhLQBRhMAAABIARksQAQkugDACQgCABA0hMQA1hMgDABQgFACBzhmQgCACBJgfQBJgfgEAAQgBAAA3ghQA6gigCgDQgBgDZChIQZBhJgBgCQgBgDBtAHQBvAHABgBQACgCBeA0QBeAzAAgBIBuC0QACADAYEDIAYECQACgCCMCDQCNCDgCAAQgBAAAvBLQAvBLgDAAQgEAAA+BgQA+BhAAgDQCHEMgFACQgEACApCuQAoCsADADQACACALCQQAKCQgDAAQgEAABCBgQBCBgACgCQACgCAkBuQAjBugDACQgDABA1DxQA1DugDgBQgCgBgXF9QgXF9gCAAQgDAAgnBkIgmBkIsCOsQsNH3AAgCQAAgBqSCwQqUCwgDgBQgFgDnuANIm2hggEguLgHuIAAAAIAAAAg");
	this.shape_3.setTransform(1473.7,301.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("EgOQAtLQmyhgACACQABABk6hpQk7hqgDAAQgFAAnbmRIhkh1Qhkh0AAADQAAAChsjWQhujZgCgBQgDgBhIj1QhJj0gCAAQgFAAAZpZIBDirQBCiqgDABQgDACgWhpQgXhqgCAAQgFAAgZl8QAAADAyjpIAyjIIBcjIQBbjHgDgCQgDgBCEi/ICDi8IBPhLQBRhMAAABIARksQAQkugDACQgCABA0hMQA1hMgDABQgFACBzhmQgCACBJgfQBJgfgEAAQgBAAA3ghQA6gigCgDQgBgDZChIQZBhJgBgCQgBgDBtAHQBvAHABgBQACgCBeA0QBeAzAAgBIBuC0QACADAYEDIAYECQACgCCMCDQCNCDgCAAQgBAAAvBLQAvBLgDAAQgEAAA+BgQA+BhAAgDQCHEMgFACQgEACApCuQAoCsADADQACACALCQQAKCQgDAAQgEAABCBgQBCBgACgCQACgCAkBuQAjBugDACQgDABA1DxQA1DugDgBQgCgBgXF9QgXF9gCAAQgDAAgnBkIgmBkIsCOsQsNH3AAgCQAAgBqSCwQqUCwgDgBQgFgDnuANIm2hggEguLgHuIAAAAIAAAAg");
	this.shape_4.setTransform(1473.7,301.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1170,1.6,607.5,599.4);


(lib.Стойка = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("Stoyka");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("EARSh4YQAAgBKFACQKFADAAgBMgPuC/nQRnhKACABQABABgaD/QgZEAAAABQACAChLCQIgQCYQAAABi2BYQAAgBicgDQicgDABABQABABg2iWQAAABh0AgQh0AgAAABQAAAAg/BqQg/BpABABQgmgEguABQhbAAgfAWQgaATgIA2QgLBGgVAkQgYArgyAaQguAYgJAXQgMAfAUHMQAJDnANDgQCVCdAAgBIAHBBQAHBOgBA+QAAAyADDSQgBC8gPAQQgUATh2AvQh3AugYgDQgbgEikhCQilhDgJgMQgLgRgEkCQgEkLATgvQASgsAugzQAWgaAUgSQAFgDgtnjQgtnpgVgSQgJgJhsglQhhghgRgiQgFgJglh4QgbhWgYAAQgVAAkugOQkngNAAABQgSFJgBACQgBABhZAFQACgBhMheIhjhRQABAAhzhWQABABk5hpIhpgXQgBABh3gPQABABiXACIipAGQgBgBhLANQgBABiKAmQABABhOAlQAAAAhjAlQABAAh3A7QAAABg1ApQABABhIAwQAAABgkAoQABABgjAlQABAAg1BNQAAABgeA8QAAABgWAgQAAAAhMAEQAAgBgyviQAAAAAOgoIgCh3UAtzgDYgABAABg");
	this.shape.setTransform(1536.1,-344);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.008)").s().p("EAPOB4aQgbgEikhCQilhDgJgMQgLgRgEkCQgEkLATgvQASgsAugzQAWgaAUgSQAFgDgtnjQgtnpgVgSQgJgJhsglQhhghgRgiQgFgJglh4QgbhWgYAAQgVAAkugOIkngMQgSFJgBACQgBABhZAFQACgBhMheIhjhRIhyhWQABABk5hpIhpgXQgBABh3gPQABABiXACIipAGIhMAMQgBABiKAmIhNAmIhjAlIh2A7Ig1AqIhHAxIgkApQABABgjAlIg0BNQAAABgeA8IgWAhIhMAEIgyvjIAOgoIgCh3UAtzgDYgABAABMAKqjACQAAgBKFACIKFACMgPuC/nQRnhKACABQABABgaD/IgZEBQACAChLCQIgQCYQAAABi2BYQAAgBicgDQiZgDgCAAIg1iUQAAABh0AgIh0AhIg/BqQg/BpABABQgmgEguABQhbAAgfAWQgaATgIA2QgLBGgVAkQgYArgyAaQguAYgJAXQgMAfAUHMQAJDnANDgICVCcIAHBBQAHBOgBA+QAAAyADDSQgBC8gPAQQgUATh2AvQhuArgdAAIgEAAgEAdfBUHIAAgBIAAABIAAAAg");
	this.shape_1.setTransform(1536.1,-344);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("EARSh4YQAAgBKFACQKFADAAgBMgPuC/nQRnhKACABQABABgaD/QgZEAAAABQACAChLCQIgQCYQAAABi2BYQAAgBicgDQicgDABABQABABg2iWQAAABh0AgQh0AgAAABQAAAAg/BqQg/BpABABQgmgEguABQhbAAgfAWQgaATgIA2QgLBGgVAkQgYArgyAaQguAYgJAXQgMAfAUHMQAJDnANDgQCVCdAAgBIAHBBQAHBOgBA+QAAAyADDSQgBC8gPAQQgUATh2AvQh3AugYgDQgbgEikhCQilhDgJgMQgLgRgEkCQgEkLATgvQASgsAugzQAWgaAUgSQAFgDgtnjQgtnpgVgSQgJgJhsglQhhghgRgiQgFgJglh4QgbhWgYAAQgVAAkugOQkngNAAABQgSFJgBACQgBABhZAFQACgBhMheIhjhRQABAAhzhWQABABk5hpIhpgXQgBABh3gPQABABiXACIipAGQgBgBhLANQgBABiKAmQABABhOAlQAAAAhjAlQABAAh3A7QAAABg1ApQABABhIAwQAAABgkAoQABABgjAlQABAAg1BNQAAABgeA8QAAABgWAgQAAAAhMAEQAAgBgyviQAAAAAOgoIgCh3UAtzgDYgABAABg");
	this.shape_2.setTransform(1536.1,-344);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("EAPOB4aQgbgEikhCQilhDgJgMQgLgRgEkCQgEkLATgvQASgsAugzQAWgaAUgSQAFgDgtnjQgtnpgVgSQgJgJhsglQhhghgRgiQgFgJglh4QgbhWgYAAQgVAAkugOIkngMQgSFJgBACQgBABhZAFQACgBhMheIhjhRIhyhWQABABk5hpIhpgXQgBABh3gPQABABiXACIipAGIhMAMQgBABiKAmIhNAmIhjAlIh2A7Ig1AqIhHAxIgkApQABABgjAlIg0BNQAAABgeA8IgWAhIhMAEIgyvjIAOgoIgCh3UAtzgDYgABAABMAKqjACQAAgBKFACIKFACMgPuC/nQRnhKACABQABABgaD/IgZEBQACAChLCQIgQCYQAAABi2BYQAAgBicgDQiZgDgCAAIg1iUQAAABh0AgIh0AhIg/BqQg/BpABABQgmgEguABQhbAAgfAWQgaATgIA2QgLBGgVAkQgYArgyAaQguAYgJAXQgMAfAUHMQAJDnANDgICVCcIAHBBQAHBOgBA+QAAAyADDSQgBC8gPAQQgUATh2AvQhuArgdAAIgEAAgEAdfBUHIAAgBIAAABIAAAAg");
	this.shape_3.setTransform(1536.1,-344);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("EAPOB4aQgbgEikhCQilhDgJgMQgLgRgEkCQgEkLATgvQASgsAugzQAWgaAUgSQAFgDgtnjQgtnpgVgSQgJgJhsglQhhghgRgiQgFgJglh4QgbhWgYAAQgVAAkugOIkngMQgSFJgBACQgBABhZAFQACgBhMheIhjhRIhyhWQABABk5hpIhpgXQgBABh3gPQABABiXACIipAGIhMAMQgBABiKAmIhNAmIhjAlIh2A7Ig1AqIhHAxIgkApQABABgjAlIg0BNQAAABgeA8IgWAhIhMAEIgyvjIAOgoIgCh3UAtzgDYgABAABMAKqjACQAAgBKFACIKFACMgPuC/nQRnhKACABQABABgaD/IgZEBQACAChLCQIgQCYQAAABi2BYQAAgBicgDQiZgDgCAAIg1iUQAAABh0AgIh0AhIg/BqQg/BpABABQgmgEguABQhbAAgfAWQgaATgIA2QgLBGgVAkQgYArgyAaQguAYgJAXQgMAfAUHMQAJDnANDgICVCcIAHBBQAHBOgBA+QAAAyADDSQgBC8gPAQQgUATh2AvQhuArgdAAIgEAAgEAdfBUHIAAgBIAAABIAAAAg");
	this.shape_4.setTransform(1536.1,-344);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1283.2,-1115.6,505.8,1543.1);


(lib.Ручкабарабана = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("BARABAN");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("AtrvAQgEAABYgDQBVgEgBgBQgBgBBBgTQBAgUAAAAQABgCFnAKQASADAYAQQAvAfAfA+QAgA+AvB6QAmBmACAKQABACAKBGQABAAE4ACQgBABFCgDQABAADugEQBcCDAAAnQAAALAZCjQAXCXgGAXQgDALgEC6QgDCwgPAWQgRAagmAZQghAVgRACQgLABmiAKQmgAKAAAAQAAAsgFA5QgJBxgWA6QgaBGgdA8QgeA6gOAJQgTAMgiAQQAAAAijgDQiygIhIgVQhyghBAATQgBgBgBAYQgBAAgOAdQgvACgBAAIikAVIhxl8QhvmGARgwQAGgTgJidQgMjQAAh8QACnnCiidg");
	this.shape.setTransform(-454,-163.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("AuiJ2QhvmGARgwQAGgTgJidQgMjQAAh8QACnnCiidIBUgDQBVgEgBgBQgBgBBBgTIBAgUQABgCFnAKQASADAYAQQAvAfAfA+QAgA+AvB6QAmBmACAKIALBIIE5ACQgBABFCgDIDvgEQBcCDAAAnQAAALAZCjQAXCXgGAXQgDALgEC6QgDCwgPAWQgRAagmAZQghAVgRACQgLABmiAKImgAKQAAAsgFA5QgJBxgWA6QgaBGgdA8QgeA6gOAJQgTAMgiAQIijgDQiygIhIgVIgygOIgCAXQgBAAgOAdIgwACIikAVgApMOnIAAAAIAAAAgAtrvAIAAAAIAAAAg");
	this.shape_1.setTransform(-454,-163.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("AtrvAQgEAABYgDQBVgEgBgBQgBgBBBgTQBAgUAAAAQABgCFnAKQASADAYAQQAvAfAfA+QAgA+AvB6QAmBmACAKQABACAKBGQABAAE4ACQgBABFCgDQABAADugEQBcCDAAAnQAAALAZCjQAXCXgGAXQgDALgEC6QgDCwgPAWQgRAagmAZQghAVgRACQgLABmiAKQmgAKAAAAQAAAsgFA5QgJBxgWA6QgaBGgdA8QgeA6gOAJQgTAMgiAQQAAAAijgDQiygIhIgVQhyghBAATQgBgBgBAYQgBAAgOAdQgvACgBAAIikAVIhxl8QhvmGARgwQAGgTgJidQgMjQAAh8QACnnCiidg");
	this.shape_2.setTransform(-454,-163.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("AuiJ2QhvmGARgwQAGgTgJidQgMjQAAh8QACnnCiidIBUgDQBVgEgBgBQgBgBBBgTIBAgUQABgCFnAKQASADAYAQQAvAfAfA+QAgA+AvB6QAmBmACAKIALBIIE5ACQgBABFCgDIDvgEQBcCDAAAnQAAALAZCjQAXCXgGAXQgDALgEC6QgDCwgPAWQgRAagmAZQghAVgRACQgLABmiAKImgAKQAAAsgFA5QgJBxgWA6QgaBGgdA8QgeA6gOAJQgTAMgiAQIijgDQiygIhIgVIgygOIgCAXQgBAAgOAdIgwACIikAVgApMOnIAAAAIAAAAgAtrvAIAAAAIAAAAg");
	this.shape_3.setTransform(-454,-163.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("AuiJ2QhvmGARgwQAGgTgJidQgMjQAAh8QACnnCiidIBUgDQBVgEgBgBQgBgBBBgTIBAgUQABgCFnAKQASADAYAQQAvAfAfA+QAgA+AvB6QAmBmACAKIALBIIE5ACQgBABFCgDIDvgEQBcCDAAAnQAAALAZCjQAXCXgGAXQgDALgEC6QgDCwgPAWQgRAagmAZQghAVgRACQgLABmiAKImgAKQAAAsgFA5QgJBxgWA6QgaBGgdA8QgeA6gOAJQgTAMgiAQIijgDQiygIhIgVIgygOIgCAXQgBAAgOAdIgwACIikAVgApMOnIAAAAIAAAAgAtrvAIAAAAIAAAAg");
	this.shape_4.setTransform(-454,-163.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-559,-265.8,209.9,203.9);


(lib.Предметныйстолик = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("Stolik");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("AXQrPMghngCgQgBAAm0MMQm0MMABgBUAABAAAAjGADIQADAAM14vQgBACgXgIQgMgFgMgFg");
	this.shape.setTransform(-906.4,348);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("A3/KoIGzsLQG0sMABAAMAhnACgIAXAJQAYAJABgCQs1YvgDAAMgjHgDIg");
	this.shape_1.setTransform(-906.4,348);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("AXQrPMghngCgQgBAAm0MMQm0MMABgBUAABAAAAjGADIQADAAM14vQgBACgXgIQgMgFgMgFg");
	this.shape_2.setTransform(-906.4,348);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("A3/KoIGzsLQG0sMABAAMAhnACgIAXAJQAYAJABgCQs1YvgDAAMgjHgDIg");
	this.shape_3.setTransform(-906.4,348);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("A3/KoIGzsLQG0sMABAAMAhnACgIAXAJQAYAJABgCQs1YvgDAAMgjHgDIg");
	this.shape_4.setTransform(-906.4,348);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1061,259,309.2,178);


(lib.Микроскоп = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("Microscope");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("AeTwUQACADADAHQAQAlApCJIBXC1QgBAAgPBLQgQBLABAAQgFA0gBAAQgBAAGGC4QAEAAAIAXQALAdgHAjQgGAbgBAmQgJAjg6A5Qg5A4jGhpQhjg0hXhAQkYKAgBAAQC0J2gBgBQAOAGAcAQQA6AhBEAyQBEAzAFAbQADAOgLADQABAAHDgLIBRhZIAblOQgDgMAGgQQAMggAqgSQAqgTA+AOQA1ASABAAQABAABtBRQAUA8ABAAQATgDATgBQAngBAHANQAGALARBmQAUB3ANB6QAlFog1B8Qg0B6gJBCQgEAiAHAJQg2B6ABABQABABhYAFIhZAFQgwhdABABQh7gPAAgBIgWhGQgWhFgBAAQAAABAHhqQAHhpgBAAQmqANABAAQCQHUAAAAQBkAHBwAPQDfAfA7ApQA5AoC5CUQCsCKABAAQABgBCcECQABABCpF3QCrGTANCNQAFA4AdDKQAkDyAQCKQBBIRgfEUQgsGNiLJxQicK/hwC9QgoBFgzBWQgkA2ggAOQghAOhEgKQgGAAi5gkQjTgphsiSQgigugSgxQgRguAHAHQAEAEgUjZQgUjYgEgCQgDgBA2ixQBKjrAkh2QAuiXATj5QAHhYAIj+QADhigLirIgMiXQhoB0AAAAIiYB7QjACWjGCBQp4GgnEBAQnCBAjvATQh2AKgbgCImFgdQABAAjXH4QjcIUgSCGQgRCDhoBYQgZAVgoAZQgYAQAFACQAJAEgTALQgVANglAMQhmAgh1gCQhvgDiHg9QhDgegtgdQgmiWgpibQhSk2gPgaQgOgXD8rBQD2qxgMAJQgWARjqiVQjqiVgDgjQgCgbg1hXQgwhOADAAQgWgqgfhOQg/iegMikQgMinALg6QAEgSAFgGIAEgBQAAgBAMg8IhHgaIg+hmQgCgCBhjOQBijNAKALQALAKAcglQAagnAAAAQgBAACoglQBKhOBthoQDcjQCyiBQDXicEiiPQEjiQCxglQCRgfEMhRQDshKgBABIDVjqQgYgzgVhDQgqiGAShRQAShSAFhiQAFhRgEgCQAAAAAogfQAngfgBAAQgCAAjsriIlLvpIhKijQhPiigfAHQgfAHgbAbQgOANgHALQgaAnAAAAQidBoAAgBQgoBCAAAAIgnCIQghBughBGIgwA7Qg/BGhKA5QjtCzkDgbQkDgchHhHQgjgkAPgeIiJhkQgKgGgMgZQgagygNhcQgViUhrl9ImEACQgBAAABgRQACgWgDgQQgJg1g9AIQhhAMpegWQACgChmgTQgzgKgxgJQABAAicl1Qidl2AAADQAAACiVgCQixgBhBABQgrABgnhPQgihGgWhtQgUhnABhVQABhaAZgRQAtgeCSgOQCGgNAGAHQADADhakCQhakCgDABQgKABCRkPQCTkTAxgbQAzgcBngZQBdgWAEAEQACACgKjsQgKjsgCgCQgCgBhelJQhflKAAgDQABgCiuhJQi1hVglg8Qgkg7h+mBQg+i/g6izQgGACB/jVQAYgohRg/QgogfgsgaQABgBg9gxQhLg/g6g9QjBjLAPicQAOicgTgxQgKgYgMAGQABAAAGgoQAJgyAPguQAviXBXhJQB0hhB8hMQCMhXA+gCQBpgLA8gEQBvgHA7AbQBLAjBIAdQBOAfAlAIQAdAHBHgVQBVgaAPgBQAegDC3gEICtgDQAwACBDAMQCEAYBYAxQBhA3CeCBQCOB0BBBGQA0A3BLClQBECUALA2QAHAlAZA6IAXAzQAkAMAtASQBaAlAkAfQAkAfAgBIQAbA+gEAFQAAABApB5QAqB4gBABQgBABB0GfQgMAkgSAwQgiBggcAxQgsBRg9BNQAAAACEGqQCDGqAAAAQAcACAnAEQBQAIAxAJQAzAJAKgyQAFgZgEgbQAAABDxh7QBQgeBUgcQCpg4AZAGQALADBIgEQBmgFAxgBQDegDBNAvQBPAxBQBIIBBA+IAmBWQgBAAA/B6IAEAqIMfCPIDsAaQAnAKA7ASQB3AkBqAsQBrArBJAtIAzAjQgBgBAZAjQABABDWAkIAIAQQAUAjAmBOQAoBRAgBRIAZBAQAAAAHOgQQATADAcAUQA4AnAvBQQAuBPAdCNQAUB8gBAAQAAgBOKAgQAUAgAVAmQArBNAFAgQAKA7AGETQAGEtgTAlQgVAngYAnQgWAkgBgBQgBgBm2APQm2APAAAAQAAAzgIBDQgRCGgsBJQgsBJgvA1QgYAbgQAMQAAABjhAAQjigFgOgbQgNgbgYBAQgUBGAAAAIjDAYQoxAZgqABIgDAAQAAgFADAFg");
	this.shape.setTransform(-833.1,78);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("EgRnBz3QhvgDiHg9QhDgegtgdIhPkxQhSk2gPgaQgOgXD8rBQD2qxgMAJQgWARjqiVQjqiVgDgjQgCgbg1hXQgwhOADAAQgWgqgfhOQg/iegMikQgMinALg6QAEgSAFgGIAEgBIAMg9IhHgaIg+hmQgCgCBhjOQBijNAKALQALAKAcglIAagnICnglQBKhOBthoQDcjQCyiBQDXicEiiPQEjiQCxglQCRgfEMhRIDrhJIDVjqQgYgzgVhDQgqiGAShRQAShSAFhiQAFhRgEgCIAogfIAmgfQgCAAjsriIlLvpIhKijQhPiigfAHQgfAHgbAbQgOANgHALIgaAnQidBoAAgBIgoBCIgnCIQghBughBGIgwA7Qg/BGhKA5QjtCzkDgbQkDgchHhHQgjgkAPgeIiJhkQgKgGgMgZQgagygNhcQgViUhrl9ImEACIAAgRQACgWgDgQQgJg1g9AIQhhAMpegWQACgChmgTIhkgTQABAAicl1IidlzQAAACiVgCQixgBhBABQgrABgnhPQgihGgWhtQgUhnABhVQABhaAZgRQAtgeCSgOQCGgNAGAHQADADhakCQhakCgDABQgKABCRkPQCTkTAxgbQAzgcBngZQBdgWAEAEQACACgKjsQgKjsgCgCQgCgBhelJQhflKAAgDQABgCiuhJQi1hVglg8Qgkg7h+mBIh4lyQgGACB/jVQAYgohRg/QgogfgsgaQABgBg9gxQhLg/g6g9QjBjLAPicQAOicgTgxQgKgYgMAGIAHgoQAJgyAPguQAviXBXhJQB0hhB8hMQCMhXA+gCQBpgLA8gEQBvgHA7AbQBLAjBIAdQBOAfAlAIQAdAHBHgVQBVgaAPgBQAegDC3gEICtgDQAwACBDAMQCEAYBYAxQBhA3CeCBQCOB0BBBGQA0A3BLClQBECUALA2QAHAlAZA6IAXAzQAkAMAtASQBaAlAkAfQAkAfAgBIQAbA+gEAFQAAABApB5IApB5QgBABB0GfQgMAkgSAwQgiBggcAxQgsBRg9BNICEGqICDGqIBDAGQBQAIAxAJQAzAJAKgyQAFgZgEgbIDxh6QBQgeBUgcQCpg4AZAGQALADBIgEQBmgFAxgBQDegDBNAvQBPAxBQBIIBBA+IAmBWQgBAAA/B6IAEAqIMfCPIDsAaQAnAKA7ASQB3AkBqAsQBrArBJAtIAzAjIAYAiQABABDWAkIAIAQQAUAjAmBOQAoBRAgBRIAZBAIHOgQQATADAcAUQA4AnAvBQQAuBPAdCNIATB8IAAAAIAAAAQADgBOHAgQAUAgAVAmQArBNAFAgQAKA7AGETQAGEtgTAlQgVAngYAnQgWAkgBgBQgBgBm2APIm2APQAAAzgIBDQgRCGgsBJQgsBJgvA1QgYAbgQAMIjhABQjigFgOgbQgNgbgYBAIgUBGIjDAYIpbAaQgDgFAAAFIADAAIAFAKQAQAlApCJIBXC1QgBAAgPBLIgPBLQgFA0gBAAIGFC4QAEAAAIAXQALAdgHAjQgGAbgBAmQgJAjg6A5Qg5A4jGhpQhjg0hXhAIkZKAQC0J2gBgBQAOAGAcAQQA6AhBEAyQBEAzAFAbQADAOgLADIHEgLIBRhZIAblOQgDgMAGgQQAMggAqgSQAqgTA+AOIA2ASIBuBRQAUA8ABAAQATgDATgBQAngBAHANQAGALARBmQAUB3ANB6QAlFog1B8Qg0B6gJBCQgEAiAHAJQg2B6ABABIhXAGIhZAFIgvhcIAAAAIAAAAIh7gQIgWhGQgWhFgBAAIAHhpQAHhpgBAAImpANICQHUQBkAHBwAPQDfAfA7ApQA5AoC5CUICtCKQABgBCcECICqF4QCrGTANCNQAFA4AdDKQAkDyAQCKQBBIRgfEUQgsGNiLJxQicK/hwC9IhbCbQgkA2ggAOQghAOhEgKIi/gkQjTgphsiSQgigugSgxQgRguAHAHQAEAEgUjZQgUjYgEgCQgDgBA2ixIBulhQAuiXATj5QAHhYAIj+QADhigLirIgMiXIhoB0IiYB7QjACWjGCBQp4GgnEBAQnCBAjvATQh2AKgbgCImFgdIjWH4QjcIUgSCGQgRCDhoBYQgZAVgoAZQgYAQAFACQAJAEgTALQgVANglAMQhfAehrAAIgRAAgEgbXA06IAAAAIAAAAgEhFChp4IAAAAIAAAAg");
	this.shape_1.setTransform(-833.1,78);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("AeTwUQACADADAHQAQAlApCJIBXC1QgBAAgPBLQgQBLABAAQgFA0gBAAQgBAAGGC4QAEAAAIAXQALAdgHAjQgGAbgBAmQgJAjg6A5Qg5A4jGhpQhjg0hXhAQkYKAgBAAQC0J2gBgBQAOAGAcAQQA6AhBEAyQBEAzAFAbQADAOgLADQABAAHDgLIBRhZIAblOQgDgMAGgQQAMggAqgSQAqgTA+AOQA1ASABAAQABAABtBRQAUA8ABAAQATgDATgBQAngBAHANQAGALARBmQAUB3ANB6QAlFog1B8Qg0B6gJBCQgEAiAHAJQg2B6ABABQABABhYAFIhZAFQgwhdABABQh7gPAAgBIgWhGQgWhFgBAAQAAABAHhqQAHhpgBAAQmqANABAAQCQHUAAAAQBkAHBwAPQDfAfA7ApQA5AoC5CUQCsCKABAAQABgBCcECQABABCpF3QCrGTANCNQAFA4AdDKQAkDyAQCKQBBIRgfEUQgsGNiLJxQicK/hwC9QgoBFgzBWQgkA2ggAOQghAOhEgKQgGAAi5gkQjTgphsiSQgigugSgxQgRguAHAHQAEAEgUjZQgUjYgEgCQgDgBA2ixQBKjrAkh2QAuiXATj5QAHhYAIj+QADhigLirIgMiXQhoB0AAAAIiYB7QjACWjGCBQp4GgnEBAQnCBAjvATQh2AKgbgCImFgdQABAAjXH4QjcIUgSCGQgRCDhoBYQgZAVgoAZQgYAQAFACQAJAEgTALQgVANglAMQhmAgh1gCQhvgDiHg9QhDgegtgdQgmiWgpibQhSk2gPgaQgOgXD8rBQD2qxgMAJQgWARjqiVQjqiVgDgjQgCgbg1hXQgwhOADAAQgWgqgfhOQg/iegMikQgMinALg6QAEgSAFgGIAEgBQAAgBAMg8IhHgaIg+hmQgCgCBhjOQBijNAKALQALAKAcglQAagnAAAAQgBAACoglQBKhOBthoQDcjQCyiBQDXicEiiPQEjiQCxglQCRgfEMhRQDshKgBABIDVjqQgYgzgVhDQgqiGAShRQAShSAFhiQAFhRgEgCQAAAAAogfQAngfgBAAQgCAAjsriIlLvpIhKijQhPiigfAHQgfAHgbAbQgOANgHALQgaAnAAAAQidBoAAgBQgoBCAAAAIgnCIQghBughBGIgwA7Qg/BGhKA5QjtCzkDgbQkDgchHhHQgjgkAPgeIiJhkQgKgGgMgZQgagygNhcQgViUhrl9ImEACQgBAAABgRQACgWgDgQQgJg1g9AIQhhAMpegWQACgChmgTQgzgKgxgJQABAAicl1Qidl2AAADQAAACiVgCQixgBhBABQgrABgnhPQgihGgWhtQgUhnABhVQABhaAZgRQAtgeCSgOQCGgNAGAHQADADhakCQhakCgDABQgKABCRkPQCTkTAxgbQAzgcBngZQBdgWAEAEQACACgKjsQgKjsgCgCQgCgBhelJQhflKAAgDQABgCiuhJQi1hVglg8Qgkg7h+mBQg+i/g6izQgGACB/jVQAYgohRg/QgogfgsgaQABgBg9gxQhLg/g6g9QjBjLAPicQAOicgTgxQgKgYgMAGQABAAAGgoQAJgyAPguQAviXBXhJQB0hhB8hMQCMhXA+gCQBpgLA8gEQBvgHA7AbQBLAjBIAdQBOAfAlAIQAdAHBHgVQBVgaAPgBQAegDC3gEICtgDQAwACBDAMQCEAYBYAxQBhA3CeCBQCOB0BBBGQA0A3BLClQBECUALA2QAHAlAZA6IAXAzQAkAMAtASQBaAlAkAfQAkAfAgBIQAbA+gEAFQAAABApB5QAqB4gBABQgBABB0GfQgMAkgSAwQgiBggcAxQgsBRg9BNQAAAACEGqQCDGqAAAAQAcACAnAEQBQAIAxAJQAzAJAKgyQAFgZgEgbQAAABDxh7QBQgeBUgcQCpg4AZAGQALADBIgEQBmgFAxgBQDegDBNAvQBPAxBQBIIBBA+IAmBWQgBAAA/B6IAEAqIMfCPIDsAaQAnAKA7ASQB3AkBqAsQBrArBJAtIAzAjQgBgBAZAjQABABDWAkIAIAQQAUAjAmBOQAoBRAgBRIAZBAQAAAAHOgQQATADAcAUQA4AnAvBQQAuBPAdCNQAUB8gBAAQAAgBOKAgQAUAgAVAmQArBNAFAgQAKA7AGETQAGEtgTAlQgVAngYAnQgWAkgBgBQgBgBm2APQm2APAAAAQAAAzgIBDQgRCGgsBJQgsBJgvA1QgYAbgQAMQAAABjhAAQjigFgOgbQgNgbgYBAQgUBGAAAAIjDAYQoxAZgqABIgDAAQAAgFADAFg");
	this.shape_2.setTransform(-833.1,78);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("EgRnBz3QhvgDiHg9QhDgegtgdIhPkxQhSk2gPgaQgOgXD8rBQD2qxgMAJQgWARjqiVQjqiVgDgjQgCgbg1hXQgwhOADAAQgWgqgfhOQg/iegMikQgMinALg6QAEgSAFgGIAEgBIAMg9IhHgaIg+hmQgCgCBhjOQBijNAKALQALAKAcglIAagnICnglQBKhOBthoQDcjQCyiBQDXicEiiPQEjiQCxglQCRgfEMhRIDrhJIDVjqQgYgzgVhDQgqiGAShRQAShSAFhiQAFhRgEgCIAogfIAmgfQgCAAjsriIlLvpIhKijQhPiigfAHQgfAHgbAbQgOANgHALIgaAnQidBoAAgBIgoBCIgnCIQghBughBGIgwA7Qg/BGhKA5QjtCzkDgbQkDgchHhHQgjgkAPgeIiJhkQgKgGgMgZQgagygNhcQgViUhrl9ImEACIAAgRQACgWgDgQQgJg1g9AIQhhAMpegWQACgChmgTIhkgTQABAAicl1IidlzQAAACiVgCQixgBhBABQgrABgnhPQgihGgWhtQgUhnABhVQABhaAZgRQAtgeCSgOQCGgNAGAHQADADhakCQhakCgDABQgKABCRkPQCTkTAxgbQAzgcBngZQBdgWAEAEQACACgKjsQgKjsgCgCQgCgBhelJQhflKAAgDQABgCiuhJQi1hVglg8Qgkg7h+mBIh4lyQgGACB/jVQAYgohRg/QgogfgsgaQABgBg9gxQhLg/g6g9QjBjLAPicQAOicgTgxQgKgYgMAGIAHgoQAJgyAPguQAviXBXhJQB0hhB8hMQCMhXA+gCQBpgLA8gEQBvgHA7AbQBLAjBIAdQBOAfAlAIQAdAHBHgVQBVgaAPgBQAegDC3gEICtgDQAwACBDAMQCEAYBYAxQBhA3CeCBQCOB0BBBGQA0A3BLClQBECUALA2QAHAlAZA6IAXAzQAkAMAtASQBaAlAkAfQAkAfAgBIQAbA+gEAFQAAABApB5IApB5QgBABB0GfQgMAkgSAwQgiBggcAxQgsBRg9BNICEGqICDGqIBDAGQBQAIAxAJQAzAJAKgyQAFgZgEgbIDxh6QBQgeBUgcQCpg4AZAGQALADBIgEQBmgFAxgBQDegDBNAvQBPAxBQBIIBBA+IAmBWQgBAAA/B6IAEAqIMfCPIDsAaQAnAKA7ASQB3AkBqAsQBrArBJAtIAzAjIAYAiQABABDWAkIAIAQQAUAjAmBOQAoBRAgBRIAZBAIHOgQQATADAcAUQA4AnAvBQQAuBPAdCNIATB8IAAAAIAAAAQADgBOHAgQAUAgAVAmQArBNAFAgQAKA7AGETQAGEtgTAlQgVAngYAnQgWAkgBgBQgBgBm2APIm2APQAAAzgIBDQgRCGgsBJQgsBJgvA1QgYAbgQAMIjhABQjigFgOgbQgNgbgYBAIgUBGIjDAYIpbAaQgDgFAAAFIADAAIAFAKQAQAlApCJIBXC1QgBAAgPBLIgPBLQgFA0gBAAIGFC4QAEAAAIAXQALAdgHAjQgGAbgBAmQgJAjg6A5Qg5A4jGhpQhjg0hXhAIkZKAQC0J2gBgBQAOAGAcAQQA6AhBEAyQBEAzAFAbQADAOgLADIHEgLIBRhZIAblOQgDgMAGgQQAMggAqgSQAqgTA+AOIA2ASIBuBRQAUA8ABAAQATgDATgBQAngBAHANQAGALARBmQAUB3ANB6QAlFog1B8Qg0B6gJBCQgEAiAHAJQg2B6ABABIhXAGIhZAFIgvhcIAAAAIAAAAIh7gQIgWhGQgWhFgBAAIAHhpQAHhpgBAAImpANICQHUQBkAHBwAPQDfAfA7ApQA5AoC5CUICtCKQABgBCcECICqF4QCrGTANCNQAFA4AdDKQAkDyAQCKQBBIRgfEUQgsGNiLJxQicK/hwC9IhbCbQgkA2ggAOQghAOhEgKIi/gkQjTgphsiSQgigugSgxQgRguAHAHQAEAEgUjZQgUjYgEgCQgDgBA2ixIBulhQAuiXATj5QAHhYAIj+QADhigLirIgMiXIhoB0IiYB7QjACWjGCBQp4GgnEBAQnCBAjvATQh2AKgbgCImFgdIjWH4QjcIUgSCGQgRCDhoBYQgZAVgoAZQgYAQAFACQAJAEgTALQgVANglAMQhfAehrAAIgRAAgEgbXA06IAAAAIAAAAgEhFChp4IAAAAIAAAAg");
	this.shape_3.setTransform(-833.1,78);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("EgRnBz3QhvgDiHg9QhDgegtgdIhPkxQhSk2gPgaQgOgXD8rBQD2qxgMAJQgWARjqiVQjqiVgDgjQgCgbg1hXQgwhOADAAQgWgqgfhOQg/iegMikQgMinALg6QAEgSAFgGIAEgBIAMg9IhHgaIg+hmQgCgCBhjOQBijNAKALQALAKAcglIAagnICnglQBKhOBthoQDcjQCyiBQDXicEiiPQEjiQCxglQCRgfEMhRIDrhJIDVjqQgYgzgVhDQgqiGAShRQAShSAFhiQAFhRgEgCIAogfIAmgfQgCAAjsriIlLvpIhKijQhPiigfAHQgfAHgbAbQgOANgHALIgaAnQidBoAAgBIgoBCIgnCIQghBughBGIgwA7Qg/BGhKA5QjtCzkDgbQkDgchHhHQgjgkAPgeIiJhkQgKgGgMgZQgagygNhcQgViUhrl9ImEACIAAgRQACgWgDgQQgJg1g9AIQhhAMpegWQACgChmgTIhkgTQABAAicl1IidlzQAAACiVgCQixgBhBABQgrABgnhPQgihGgWhtQgUhnABhVQABhaAZgRQAtgeCSgOQCGgNAGAHQADADhakCQhakCgDABQgKABCRkPQCTkTAxgbQAzgcBngZQBdgWAEAEQACACgKjsQgKjsgCgCQgCgBhelJQhflKAAgDQABgCiuhJQi1hVglg8Qgkg7h+mBIh4lyQgGACB/jVQAYgohRg/QgogfgsgaQABgBg9gxQhLg/g6g9QjBjLAPicQAOicgTgxQgKgYgMAGIAHgoQAJgyAPguQAviXBXhJQB0hhB8hMQCMhXA+gCQBpgLA8gEQBvgHA7AbQBLAjBIAdQBOAfAlAIQAdAHBHgVQBVgaAPgBQAegDC3gEICtgDQAwACBDAMQCEAYBYAxQBhA3CeCBQCOB0BBBGQA0A3BLClQBECUALA2QAHAlAZA6IAXAzQAkAMAtASQBaAlAkAfQAkAfAgBIQAbA+gEAFQAAABApB5IApB5QgBABB0GfQgMAkgSAwQgiBggcAxQgsBRg9BNICEGqICDGqIBDAGQBQAIAxAJQAzAJAKgyQAFgZgEgbIDxh6QBQgeBUgcQCpg4AZAGQALADBIgEQBmgFAxgBQDegDBNAvQBPAxBQBIIBBA+IAmBWQgBAAA/B6IAEAqIMfCPIDsAaQAnAKA7ASQB3AkBqAsQBrArBJAtIAzAjIAYAiQABABDWAkIAIAQQAUAjAmBOQAoBRAgBRIAZBAIHOgQQATADAcAUQA4AnAvBQQAuBPAdCNIATB8IAAAAIAAAAQADgBOHAgQAUAgAVAmQArBNAFAgQAKA7AGETQAGEtgTAlQgVAngYAnQgWAkgBgBQgBgBm2APIm2APQAAAzgIBDQgRCGgsBJQgsBJgvA1QgYAbgQAMIjhABQjigFgOgbQgNgbgYBAIgUBGIjDAYIpbAaQgDgFAAAFIADAAIAFAKQAQAlApCJIBXC1QgBAAgPBLIgPBLQgFA0gBAAIGFC4QAEAAAIAXQALAdgHAjQgGAbgBAmQgJAjg6A5Qg5A4jGhpQhjg0hXhAIkZKAQC0J2gBgBQAOAGAcAQQA6AhBEAyQBEAzAFAbQADAOgLADIHEgLIBRhZIAblOQgDgMAGgQQAMggAqgSQAqgTA+AOIA2ASIBuBRQAUA8ABAAQATgDATgBQAngBAHANQAGALARBmQAUB3ANB6QAlFog1B8Qg0B6gJBCQgEAiAHAJQg2B6ABABIhXAGIhZAFIgvhcIAAAAIAAAAIh7gQIgWhGQgWhFgBAAIAHhpQAHhpgBAAImpANICQHUQBkAHBwAPQDfAfA7ApQA5AoC5CUICtCKQABgBCcECICqF4QCrGTANCNQAFA4AdDKQAkDyAQCKQBBIRgfEUQgsGNiLJxQicK/hwC9IhbCbQgkA2ggAOQghAOhEgKIi/gkQjTgphsiSQgigugSgxQgRguAHAHQAEAEgUjZQgUjYgEgCQgDgBA2ixIBulhQAuiXATj5QAHhYAIj+QADhigLirIgMiXIhoB0IiYB7QjACWjGCBQp4GgnEBAQnCBAjvATQh2AKgbgCImFgdIjWH4QjcIUgSCGQgRCDhoBYQgZAVgoAZQgYAQAFACQAJAEgTALQgVANglAMQhfAehrAAIgRAAgEgbXA06IAAAAIAAAAgEhFChp4IAAAAIAAAAg");
	this.shape_4.setTransform(-833.1,78);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1276,-664.5,885.7,1485);


(lib.Колба = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("Kolba");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("EgD2h7hUAvPAATgAJAAGUgAGAADgRABlTUgQ2BkVgAKAA3QADgDAygJQA4gJgDACQAMC1AAgBQKNFsADADQACABAJNOQAFGmAEGmIwrEvQwqEvgBgCQgBgBvvoRQvtoRAAgCQACgGBpsrQBrsvgCgBQgBAACyhrQCzhsgCADQgBABC5hUQC7hVACABQABAABPACQBQADABABUAACAADAWLjHKg");
	this.shape.setTransform(2235.4,790.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(66,66,66,0.02)").s().p("EgLyB7hIvwoSQvtoRAAgCIBrsxQBrsvgCgBQgBAACyhrQCzhsgCADIC4hTQC7hVACABIBQACQBQADABABUAACAADAWLjHJUAvPAASgAJAAGUgAGAADgRABlTMgRABlMQADgDAygJQA4gJgDACIAMC0IKQFvQACABAJNOIAJNMIwrEvQwkEtgHABIAAgBg");
	this.shape_1.setTransform(2235.4,790.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("EgD2h7hUAvPAATgAJAAGUgAGAADgRABlTUgQ2BkVgAKAA3QADgDAygJQA4gJgDACQAMC1AAgBQKNFsADADQACABAJNOQAFGmAEGmIwrEvQwqEvgBgCQgBgBvvoRQvtoRAAgCQACgGBpsrQBrsvgCgBQgBAACyhrQCzhsgCADQgBABC5hUQC7hVACABQABAABPACQBQADABABUAACAADAWLjHKg");
	this.shape_2.setTransform(2235.4,790.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("EgLyB7hIvwoSQvtoRAAgCIBrsxQBrsvgCgBQgBAACyhrQCzhsgCADIC4hTQC7hVACABIBQACQBQADABABUAACAADAWLjHJUAvPAASgAJAAGUgAGAADgRABlTMgRABlMQADgDAygJQA4gJgDACIAMC0IKQFvQACABAJNOIAJNMIwrEvQwkEtgHABIAAgBg");
	this.shape_3.setTransform(2235.4,790.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("EgLyB7hIvwoSQvtoRAAgCIBrsxQBrsvgCgBQgBAACyhrQCzhsgCADIC4hTQC7hVACABIBQACQBQADABABUAACAADAWLjHJUAvPAASgAJAAGUgAGAADgRABlTMgRABlMQADgDAygJQA4gJgDACIAMC0IKQFvQACABAJNOIAJNMIwrEvQwkEtgHABIAAgBg");
	this.shape_4.setTransform(2235.4,790.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1957.6,-0.9,555.6,1583.1);


(lib.Кнопка = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("KnopkUS");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("AQ1B3QgfFqlTDlQidBqjKAcQihAXj9gWQkBgXifgxQjLhAiJiDQiNiIhEjPQg/i/AQi+QAPisBYh2QBLhlC2h6QFTjlHAAnQDdATDWBhQDQBfCWCQQCNCIAwCYQArCFgRDAg");
	this.shape.setTransform(739,685.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("AhCNNQkBgXifgxQjLhAiJiDQiNiIhEjPQg/i/AQi+QAPisBYh2QBLhlC2h6QFTjlHAAnQDdATDWBhQDQBfCWCQQCNCIAwCYQArCFgRDAQgfFqlTDlQidBqjKAcQhRAMhqAAQhmAAh9gLg");
	this.shape_1.setTransform(739,685.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("AQ1B3QgfFqlTDlQidBqjKAcQihAXj9gWQkBgXifgxQjLhAiJiDQiNiIhEjPQg/i/AQi+QAPisBYh2QBLhlC2h6QFTjlHAAnQDdATDWBhQDQBfCWCQQCNCIAwCYQArCFgRDAg");
	this.shape_2.setTransform(739,685.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("AhCNNQkBgXifgxQjLhAiJiDQiNiIhEjPQg/i/AQi+QAPisBYh2QBLhlC2h6QFTjlHAAnQDdATDWBhQDQBfCWCQQCNCIAwCYQArCFgRDAQgfFqlTDlQidBqjKAcQhRAMhqAAQhmAAh9gLg");
	this.shape_3.setTransform(739,685.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("AhCNNQkBgXifgxQjLhAiJiDQiNiIhEjPQg/i/AQi+QAPisBYh2QBLhlC2h6QFTjlHAAnQDdATDWBhQDQBfCWCQQCNCIAwCYQArCFgRDAQgfFqlTDlQidBqjKAcQhRAMhqAAQhmAAh9gLg");
	this.shape_4.setTransform(739,685.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(629.8,599.3,218.4,173.1);


(lib.Блокпитания = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("BP");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(1));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("Egbsgh0UAB7gAVAqxgAyQA5ARA4AQQBwAhgBgCQgCgECKA8QACAAAzAoQA0AngBABQgCAABEBhQBEBgACgBQACgCA+FiQAqCNgCADQgBABABA7QABA7gBABQgBABABA7QABA7gBABQgCACBEgJQBEgIACgBQABgBAxASQAwAQgCgBQA4AxAAgBQAfBrABAFQACAAAsAaQAxAeAZAoQgBAAAVg/QAVhAgBgBQgCgBEDgNQECgMgDACQgCABAqA7QAqA7gCABQgCABAFBPQAGBPgBABQgBABABBwQABBwgBgBQgBgBgCBRQgDBRgCgBQA+ApACgBQABgBgBA9QgBA9gnAfQABgDAMD4QAMD5gBABQgBAAgqBdQgrBdgCgCQgEgEjcAUIhXADQhXADgCACQgEACh0hCQgCgCgPgwQgOgvgBABQhOBBgCgBQgCgBgjAYQgjAYAAABIAADIQimBDgCgDQgCgDg9gbQg+gcgDACQgCABgjEkQgiEjgBAAQgBgBg4BlIg3BkQAAgBg5AmQg4AlABgCQABgChRA+QhRA+ABgCQABgDhRAhQhSAgACACQABABhUAkQgrARgqASQkegigCACQgCABggCVQggCVACgDQABgClVAZQlVAZABAAQABgCgbgPQgbgPgCAAQgBAAgThNQgThMgBABQgBABgCgYQgDgZgCAAQk8gGgEgCQgCgBAFBUQAGBVgBAAQgBAAgnAlQgnAkgBgBQgBgBhxASQhvARABgCQABgCjTAZQjUAagCgBQgDgBgihPQgjhQAAAAQgCgCAIhzQAIhzACAAQrkAogEAAQjhhcABgEQAAgDhDgvQhDgwgCACQgCABgmhVQgnhUgBAAQgCAAhLkvQhLkxAAAAQhPgngBgBQgCgChGi2QAAABhngVQhogWgBACQgCACAKiiQAAABB1ATQBuASAFACQgBgFAJhbQAAgCAAhOQAAgBhngCQhogDgBgCQhPhjgBADQgBACAHhwQAIhwACgCQACgEAWhjICwgwQACgCHO5+IAUgrQAVgugBABIAogvQApgvgBgCQgCgEBihKQABABBBgiQAAABBigoQABgBBegqg");
	this.shape.setTransform(-152,131.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(32,118,204,0.008)").s().p("EgRvAi8QgDgBgihPIgjhQQgCgCAIhzQAIhzACAAIroAoQjhhcABgEQAAgDhDgvQhDgwgCACQgCABgmhVQgnhUgBAAQgCAAhLkvIhLkxIhQgoQgCgChGi2QAAABhngVQhogWgBACQgCACAKiiQAAABB1ATQBuASAFACQgBgFAJhbIAAhQIhngDQhogDgBgCQhPhjgBADQgBACAHhwQAIhwACgCQACgEAWhjICwgwQACgCHO5+IAUgrIAUgtIAogvQApgvgBgCQgCgEBihKIBCghQAAABBigoIBfgrUAB7gAVAqxgAyIBxAhQBwAhgBgCQgCgECKA8QACAAAzAoQA0AngBABQgCAABEBhQBEBgACgBQACgCA+FiQAqCNgCADQgBABABA7QABA7gBABQgBABABA7QABA7gBABQgCACBEgJQBEgIACgBQABgBAxASIAuAPQA4AxAAgBQAfBrABAFQACAAAsAaQAxAeAZAoIAAAAIAAAAQgBgCAVg9QAVhAgBgBQgCgBEDgNQECgMgDACQgCABAqA7QAqA7gCABQgCABAFBPQAGBPgBABQgBABABBwQABBwgBgBIgDBQQgDBRgCgBQA+ApACgBQABgBgBA9QgBA9gnAfIAAAAIAAAAQABAAAMD1QAMD5gBABIgrBdQgrBdgCgCQgEgEjcAUIhXADQhXADgCACQgEACh0hCQgCgCgPgwQgOgvgBABQhOBBgCgBQgCgBgjAYIgjAZIAADIQimBDgCgDQgCgDg9gbQg+gcgDACQgCABgjEkQgiEjgBAAQgBgBg4BlIg3BkIg5AlQg4AlABgCIhQA8QhRA+ABgCQABgDhRAhQhSAgACACQABABhUAkIhVAjQkegigCACQgCABggCVIgeCSQgFgClPAZIlUAZQABgCgbgPQgbgPgCAAQgBAAgThNQgThMgBABQgBABgCgYQgDgZgCAAQk8gGgEgCQgCgBAFBUQAGBVgBAAIgoAlQgnAkgBgBQgBgBhxASQhvARABgCQABgCjTAZQjMAZgKAAIAAAAgEAKwAg8IAAAAIAAAAIAAAAgAfoxDIAAAAIAAAAg");
	this.shape_1.setTransform(-152,131.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000066").ss(10,1,1).p("Egbsgh0UAB7gAVAqxgAyQA5ARA4AQQBwAhgBgCQgCgECKA8QACAAAzAoQA0AngBABQgCAABEBhQBEBgACgBQACgCA+FiQAqCNgCADQgBABABA7QABA7gBABQgBABABA7QABA7gBABQgCACBEgJQBEgIACgBQABgBAxASQAwAQgCgBQA4AxAAgBQAfBrABAFQACAAAsAaQAxAeAZAoQgBAAAVg/QAVhAgBgBQgCgBEDgNQECgMgDACQgCABAqA7QAqA7gCABQgCABAFBPQAGBPgBABQgBABABBwQABBwgBgBQgBgBgCBRQgDBRgCgBQA+ApACgBQABgBgBA9QgBA9gnAfQABgDAMD4QAMD5gBABQgBAAgqBdQgrBdgCgCQgEgEjcAUIhXADQhXADgCACQgEACh0hCQgCgCgPgwQgOgvgBABQhOBBgCgBQgCgBgjAYQgjAYAAABIAADIQimBDgCgDQgCgDg9gbQg+gcgDACQgCABgjEkQgiEjgBAAQgBgBg4BlIg3BkQAAgBg5AmQg4AlABgCQABgChRA+QhRA+ABgCQABgDhRAhQhSAgACACQABABhUAkQgrARgqASQkegigCACQgCABggCVQggCVACgDQABgClVAZQlVAZABAAQABgCgbgPQgbgPgCAAQgBAAgThNQgThMgBABQgBABgCgYQgDgZgCAAQk8gGgEgCQgCgBAFBUQAGBVgBAAQgBAAgnAlQgnAkgBgBQgBgBhxASQhvARABgCQABgCjTAZQjUAagCgBQgDgBgihPQgjhQAAAAQgCgCAIhzQAIhzACAAQrkAogEAAQjhhcABgEQAAgDhDgvQhDgwgCACQgCABgmhVQgnhUgBAAQgCAAhLkvQhLkxAAAAQhPgngBgBQgCgChGi2QAAABhngVQhogWgBACQgCACAKiiQAAABB1ATQBuASAFACQgBgFAJhbQAAgCAAhOQAAgBhngCQhogDgBgCQhPhjgBADQgBACAHhwQAIhwACgCQACgEAWhjICwgwQACgCHO5+IAUgrQAVgugBABIAogvQApgvgBgCQgCgEBihKQABABBBgiQAAABBigoQABgBBegqg");
	this.shape_2.setTransform(-152,131.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(32,118,204,0.298)").s().p("EgRvAi8QgDgBgihPIgjhQQgCgCAIhzQAIhzACAAIroAoQjhhcABgEQAAgDhDgvQhDgwgCACQgCABgmhVQgnhUgBAAQgCAAhLkvIhLkxIhQgoQgCgChGi2QAAABhngVQhogWgBACQgCACAKiiQAAABB1ATQBuASAFACQgBgFAJhbIAAhQIhngDQhogDgBgCQhPhjgBADQgBACAHhwQAIhwACgCQACgEAWhjICwgwQACgCHO5+IAUgrIAUgtIAogvQApgvgBgCQgCgEBihKIBCghQAAABBigoIBfgrUAB7gAVAqxgAyIBxAhQBwAhgBgCQgCgECKA8QACAAAzAoQA0AngBABQgCAABEBhQBEBgACgBQACgCA+FiQAqCNgCADQgBABABA7QABA7gBABQgBABABA7QABA7gBABQgCACBEgJQBEgIACgBQABgBAxASIAuAPQA4AxAAgBQAfBrABAFQACAAAsAaQAxAeAZAoIAAAAIAAAAQgBgCAVg9QAVhAgBgBQgCgBEDgNQECgMgDACQgCABAqA7QAqA7gCABQgCABAFBPQAGBPgBABQgBABABBwQABBwgBgBIgDBQQgDBRgCgBQA+ApACgBQABgBgBA9QgBA9gnAfIAAAAIAAAAQABAAAMD1QAMD5gBABIgrBdQgrBdgCgCQgEgEjcAUIhXADQhXADgCACQgEACh0hCQgCgCgPgwQgOgvgBABQhOBBgCgBQgCgBgjAYIgjAZIAADIQimBDgCgDQgCgDg9gbQg+gcgDACQgCABgjEkQgiEjgBAAQgBgBg4BlIg3BkIg5AlQg4AlABgCIhQA8QhRA+ABgCQABgDhRAhQhSAgACACQABABhUAkIhVAjQkegigCACQgCABggCVIgeCSQgFgClPAZIlUAZQABgCgbgPQgbgPgCAAQgBAAgThNQgThMgBABQgBABgCgYQgDgZgCAAQk8gGgEgCQgCgBAFBUQAGBVgBAAIgoAlQgnAkgBgBQgBgBhxASQhvARABgCQABgCjTAZQjMAZgKAAIAAAAgEAKwAg8IAAAAIAAAAIAAAAgAfoxDIAAAAIAAAAg");
	this.shape_3.setTransform(-152,131.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(32,118,204,0.6)").s().p("EgRvAi8QgDgBgihPIgjhQQgCgCAIhzQAIhzACAAIroAoQjhhcABgEQAAgDhDgvQhDgwgCACQgCABgmhVQgnhUgBAAQgCAAhLkvIhLkxIhQgoQgCgChGi2QAAABhngVQhogWgBACQgCACAKiiQAAABB1ATQBuASAFACQgBgFAJhbIAAhQIhngDQhogDgBgCQhPhjgBADQgBACAHhwQAIhwACgCQACgEAWhjICwgwQACgCHO5+IAUgrIAUgtIAogvQApgvgBgCQgCgEBihKIBCghQAAABBigoIBfgrUAB7gAVAqxgAyIBxAhQBwAhgBgCQgCgECKA8QACAAAzAoQA0AngBABQgCAABEBhQBEBgACgBQACgCA+FiQAqCNgCADQgBABABA7QABA7gBABQgBABABA7QABA7gBABQgCACBEgJQBEgIACgBQABgBAxASIAuAPQA4AxAAgBQAfBrABAFQACAAAsAaQAxAeAZAoIAAAAIAAAAQgBgCAVg9QAVhAgBgBQgCgBEDgNQECgMgDACQgCABAqA7QAqA7gCABQgCABAFBPQAGBPgBABQgBABABBwQABBwgBgBIgDBQQgDBRgCgBQA+ApACgBQABgBgBA9QgBA9gnAfIAAAAIAAAAQABAAAMD1QAMD5gBABIgrBdQgrBdgCgCQgEgEjcAUIhXADQhXADgCACQgEACh0hCQgCgCgPgwQgOgvgBABQhOBBgCgBQgCgBgjAYIgjAZIAADIQimBDgCgDQgCgDg9gbQg+gcgDACQgCABgjEkQgiEjgBAAQgBgBg4BlIg3BkIg5AlQg4AlABgCIhQA8QhRA+ABgCQABgDhRAhQhSAgACACQABABhUAkIhVAjQkegigCACQgCABggCVIgeCSQgFgClPAZIlUAZQABgCgbgPQgbgPgCAAQgBAAgThNQgThMgBABQgBABgCgYQgDgZgCAAQk8gGgEgCQgCgBAFBUQAGBVgBAAIgoAlQgnAkgBgBQgBgBhxASQhvARABgCQABgCjTAZQjMAZgKAAIAAAAgEAKwAg8IAAAAIAAAAIAAAAgAfoxDIAAAAIAAAAg");
	this.shape_4.setTransform(-152,131.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_4},{t:this.shape_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-445.8,-93,587.7,449.2);


// stage content:
(lib.map = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.Ручкабарабана();
	this.instance.parent = this;
	this.instance.setTransform(1288.1,1021.8);
	new cjs.ButtonHelper(this.instance, 0, 1, 2);

	this.instance_1 = new lib.Предметныйстолик();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1442.3,1081.2);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2);

	this.instance_2 = new lib.Микроскоп();
	this.instance_2.parent = this;
	this.instance_2.setTransform(1329.3,998.5);
	new cjs.ButtonHelper(this.instance_2, 0, 1, 2);

	this.instance_3 = new lib.Блокпитания();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1376.4,1096.8);
	new cjs.ButtonHelper(this.instance_3, 0, 1, 2);

	this.instance_4 = new lib.Таймер();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-172.5,1433.7);
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2);

	this.instance_5 = new lib.Кнопка();
	this.instance_5.parent = this;
	this.instance_5.setTransform(1210.1,1071.4);
	new cjs.ButtonHelper(this.instance_5, 0, 1, 2);

	this.instance_6 = new lib.Шарики();
	this.instance_6.parent = this;
	this.instance_6.setTransform(1303.9,724.3);
	new cjs.ButtonHelper(this.instance_6, 0, 1, 2);

	this.instance_7 = new lib.Стойка();
	this.instance_7.parent = this;
	this.instance_7.setTransform(294.5,1114.6);
	new cjs.ButtonHelper(this.instance_7, 0, 1, 2);

	this.instance_8 = new lib.Колба();
	this.instance_8.parent = this;
	this.instance_8.setTransform(6.9,0);
	new cjs.ButtonHelper(this.instance_8, 0, 1, 2);

	this.instance_9 = new lib.ustanovka();
	this.instance_9.parent = this;

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000066").ss(0.1,1,1).p("EA21hEFMAAAA5qACQQsQgbhVgghUIiwl0IhHAAIAAkJIlRjDACQQsQzRAAtpHLQtpHLAAKIEA2rgFQInQZMEgsTANOIoCAAIAAB8QhcBehDgFIGXXyIAADmIBZAAIO7SRQObJJO6lAIAAifICfAAIAAm7IDCAAQFx1amOy1");
	this.shape.setTransform(2186.7,435.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1301.5,1105,2603,2225);
// library properties:
lib.properties = {
	id: '43F19E3879C45844BFCA647D9B527722',
	width: 2603,
	height: 2220,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/ustanovka.png?1635138963088", id:"ustanovka"},
		{src:"sounds/BanochkUS.mp3?1635138963088", id:"BanochkUS"},
		{src:"sounds/BARABAN.mp3?1635138963088", id:"BARABAN"},
		{src:"sounds/BP.mp3?1635138963088", id:"BP"},
		{src:"sounds/KnopkUS.mp3?1635138963088", id:"KnopkUS"},
		{src:"sounds/Kolba.mp3?1635138963088", id:"Kolba"},
		{src:"sounds/Microscope.mp3?1635138963088", id:"Microscope"},
		{src:"sounds/Sekundomer.mp3?1635138963088", id:"Sekundomer"},
		{src:"sounds/Stolik.mp3?1635138963088", id:"Stolik"},
		{src:"sounds/Stoyka.mp3?1635138963088", id:"Stoyka"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['43F19E3879C45844BFCA647D9B527722'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;